# Site settings
title: GHGA
email: dpoubduAhihb/ef
email-data: hihb.ebubAelg{/ef
url: https://ghga.dkfz.de
description: "The German Human Genome-Phenome Archive"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark:  '#00000f'
  primary-light: '#ffffff'
  links: '#2979ff'

# Footer settings
footer: http://ghga.dkfz.de

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ghga-de/online

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-slate
